### ISSUE TITLE
Bug importing countries (id vs. name)

### ISSUE THREAD

**Issue by Luis-J-Ianez** [cubing/wca-workbook-assistant#112]
The JSON file is created with countries.name, while WA seems to be expecting countries.id.  This is a problem for "Cote d'Ivoire" and "Cote d_Ivoire".

**Comment by jfly** [comment]
> The JSON file is created with countries.name

Are you sure about this, @Luis-J-Ianez? The [WCA Competition JSON Format]() clearly says this about `countryId`: "Country codes must follow ISO 3166-1-alpha-2 codes".

Looking at the JSON for a few competitions I've been involved in, it looks like ISO2 codes indeed are generated by the WA. Code inspection tells me that WA generates ISO2 codes as well. Please see [here](https://github.com/cubing/wca-workbook-assistant/blob/2ee31b9c01443f40219ae5b7956f6a629dbb7d12/src/main/java/org/worldcubeassociation/workbook/JSONGenerator.java#L259-L272).

It's hard for me to know exactly what happened without the relevant Excel file from cubecomps, but here's my take on this. Please correct me if I'm wrong:

- This does not feel like a WA bug. The WA looks like it's doing exactly what it is was written to do: it takes a "country id" (from the WCA database, such as `Cote d_Ivoire`), and it generates JSON with a valid ISO2 code.
- Instead, this is a cubecomps bug, as cubecomps generated an excel file by filling in the country cell with a country name, rather than a country id.

I'm going to optimisitically close this issue, but please reopen if my understanding is flawed.

**Comment by Luis-J-Ianez** [comment]
Definitely, I must wait for the coffee of the morning to make effect before starting to reply emails. :P Of course, this is a Cubecomps bug!  I'll fix it ASAP.

**Comment by Luis-J-Ianez** [comment]
For your information, this is fixed in Cubecomps.
